twig:
    default_path: '%kernel.project_dir%/Templates'
    form_themes: [
        'bootstrap_4_layout.html.twig',
        'Form/CollectionDocsignaturesFormType-theme.html.twig',
        'Templates/document-theme.html.twig',
        'Form/TransactionRequestFormType-theme.html.twig',
        'Form/CollectionMailFormType-theme.html.twig',
        'Form/RedirectionConfigFormType-theme.html.twig',
        'Form/CollectionSignersFormType-theme.html.twig',
        'Form/CollectionCheckBoxTextsFormType-theme.html.twig',
        'Form/CollectionDocumentsFormType-theme.html.twig',
        'jquery.collection.html.twig']
