version: '3.7'

services:
    db:
        image: percona:8.0
        container_name: "${PROJECT_NAME}_mysql"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - Udbdata:/var/lib/mysql
            - ./mysql/config:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${BDD_PORT}:3306
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                UPSTREAMPORT: ${UPSTREAM_PORT}
        container_name: "${PROJECT_NAME}_php"
        volumes:
            #- ./php7-fpm/config/conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ${SYMFONY_APP_PATH}:/var/www/symfony
    nginx:
        build:
            context: nginx
            args:
                phpupstream: "${PROJECT_NAME}_php:${UPSTREAM_PORT}"
        container_name: "${PROJECT_NAME}_nginx"
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        depends_on:
            - php
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${PROJECT_NAME}_phpmyadmin"
        depends_on:
            - db
        ports:
            - ${PHPMYADMIN_PORT}:80
        links:
            - db
volumes:
  Udbdata:
    driver: local